services:
  nest-rtsp:
    build: .
    container_name: nest-rtsp
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "28000:28000/udp"
      - "28001:28001/udp"
    volumes:
      - ./data:/data
